import type { Alert, BrokerSetup, DocumentRecord, Holding, Sector, Stock, Transaction, WatchlistItem } from "./types";
import { portfolioMetrics } from "./scoring";

export const lastUpdated = "June 7, 2026 21:45 WAT";
export const dataSource = "Manual seed + delayed NGX-style snapshot";

export const stocks: Stock[] = [
  {
    symbol: "GTCO",
    company: "Guaranty Trust Holding Co.",
    sector: "Banking",
    price: 72.5,
    change: 1.12,
    volume: 48200000,
    marketCap: 2_130_000_000_000,
    dividendYield: 10.45,
    pe: 5.9,
    roe: 34,
    payoutRatio: 42,
    opportunityScore: 91,
    dividendScore: 88,
    valuationScore: 82,
    liquidityScore: 96,
    riskScore: 28,
    riskLevel: "Low",
    label: "Strong Dividend Candidate",
    reason: "High ROE, deep liquidity, reasonable valuation, and a strong dividend record.",
    risks: ["Banking concentration can rise quickly", "Rates and regulation can pressure margins"],
    trend: [61, 64, 62, 66, 70, 69, 72, 71, 74, 77, 75, 79],
  },
  {
    symbol: "ZENITHBANK",
    company: "Zenith Bank Plc",
    sector: "Banking",
    price: 49.8,
    change: 0.91,
    volume: 39600000,
    marketCap: 1_560_000_000_000,
    dividendYield: 9.82,
    pe: 4.8,
    roe: 31,
    payoutRatio: 38,
    opportunityScore: 88,
    dividendScore: 86,
    valuationScore: 84,
    liquidityScore: 94,
    riskScore: 30,
    riskLevel: "Low",
    label: "Strong Dividend Candidate",
    reason: "Liquid tier-one bank with attractive yield and strong earnings coverage.",
    risks: ["Sector exposure overlaps with GTCO", "FX and credit-cycle shocks remain possible"],
    trend: [45, 46, 44, 47, 48, 48, 50, 49, 52, 51, 53, 55],
  },
  {
    symbol: "UBA",
    company: "United Bank for Africa",
    sector: "Banking",
    price: 34.1,
    change: -0.58,
    volume: 29400000,
    marketCap: 1_170_000_000_000,
    dividendYield: 8.9,
    pe: 3.7,
    roe: 29,
    payoutRatio: 35,
    opportunityScore: 84,
    dividendScore: 84,
    valuationScore: 88,
    liquidityScore: 90,
    riskScore: 37,
    riskLevel: "Moderate",
    label: "Good Watchlist Candidate",
    reason: "Cheap valuation and healthy dividend profile, but cross-border risk needs review.",
    risks: ["Pan-African exposure adds currency complexity", "Price momentum softened this scan"],
    trend: [30, 31, 33, 32, 34, 36, 35, 33, 34, 33, 35, 34],
  },
  {
    symbol: "MTNN",
    company: "MTN Nigeria Communications",
    sector: "Telecom/ICT",
    price: 245,
    change: 2.34,
    volume: 9850000,
    marketCap: 4_990_000_000_000,
    dividendYield: 8.35,
    pe: 11.6,
    roe: 41,
    payoutRatio: 74,
    opportunityScore: 82,
    dividendScore: 82,
    valuationScore: 64,
    liquidityScore: 88,
    riskScore: 44,
    riskLevel: "Moderate",
    label: "Stable Defensive Candidate",
    reason: "Essential-service revenue and strong cash generation, with FX and leverage to monitor.",
    risks: ["High payout ratio leaves less cushion", "FX-linked costs can weaken earnings quality"],
    trend: [212, 218, 223, 219, 226, 232, 236, 239, 242, 238, 244, 248],
  },
  {
    symbol: "BUAFOODS",
    company: "BUA Foods Plc",
    sector: "Consumer Goods",
    price: 380,
    change: 1.06,
    volume: 3610000,
    marketCap: 6_840_000_000_000,
    dividendYield: 7.6,
    pe: 19.2,
    roe: 27,
    payoutRatio: 55,
    opportunityScore: 80,
    dividendScore: 80,
    valuationScore: 58,
    liquidityScore: 74,
    riskScore: 48,
    riskLevel: "Moderate",
    label: "Overpriced Quality Stock",
    reason: "Quality consumer franchise with income potential, but valuation is less forgiving.",
    risks: ["Premium valuation can compress", "Input costs can pressure margins"],
    trend: [340, 348, 350, 359, 354, 363, 370, 372, 369, 376, 380, 384],
  },
  {
    symbol: "DANGCEM",
    company: "Dangote Cement Plc",
    sector: "Industrial Goods",
    price: 660,
    change: 0.15,
    volume: 2200000,
    marketCap: 11_250_000_000_000,
    dividendYield: 4.5,
    pe: 16.8,
    roe: 22,
    payoutRatio: 62,
    opportunityScore: 68,
    dividendScore: 70,
    valuationScore: 52,
    liquidityScore: 78,
    riskScore: 50,
    riskLevel: "Moderate",
    label: "Stable Defensive Candidate",
    reason: "Large defensive industrial name, but entry valuation is only fair.",
    risks: ["Cement demand is cyclical", "Energy costs affect margins"],
    trend: [620, 628, 634, 639, 631, 644, 648, 655, 650, 657, 659, 660],
  },
  {
    symbol: "SEPLAT",
    company: "Seplat Energy Plc",
    sector: "Oil & Gas",
    price: 3120,
    change: -1.32,
    volume: 680000,
    marketCap: 1_840_000_000_000,
    dividendYield: 6.8,
    pe: 9.3,
    roe: 18,
    payoutRatio: 46,
    opportunityScore: 62,
    dividendScore: 73,
    valuationScore: 61,
    liquidityScore: 58,
    riskScore: 64,
    riskLevel: "Elevated",
    label: "Undervalued but Risky",
    reason: "Dividend and valuation are interesting, but oil-price and liquidity risk are higher.",
    risks: ["Commodity price volatility", "Lower trading volume than tier-one banks"],
    trend: [3150, 3180, 3125, 3190, 3210, 3175, 3140, 3185, 3160, 3135, 3120, 3110],
  },
  {
    symbol: "NESTLE",
    company: "Nestle Nigeria Plc",
    sector: "Consumer Goods",
    price: 1295,
    change: 0,
    volume: 145000,
    marketCap: 1_030_000_000_000,
    dividendYield: 3.1,
    pe: 24.5,
    roe: 16,
    payoutRatio: 80,
    opportunityScore: 47,
    dividendScore: 52,
    valuationScore: 32,
    liquidityScore: 44,
    riskScore: 70,
    riskLevel: "Elevated",
    label: "Avoid for Now",
    reason: "Quality brand, but low yield, premium valuation, and liquidity require caution.",
    risks: ["Dividend cover is thin", "Valuation is demanding"],
    trend: [1310, 1305, 1298, 1301, 1297, 1294, 1295, 1295, 1296, 1295, 1295, 1295],
  },
  {
    symbol: "OANDO",
    company: "Oando Plc",
    sector: "Oil & Gas",
    price: 10.5,
    change: -3.21,
    volume: 1260000,
    marketCap: 130_000_000_000,
    dividendYield: 0,
    pe: 0,
    roe: 8,
    payoutRatio: 0,
    opportunityScore: 31,
    dividendScore: 18,
    valuationScore: 40,
    liquidityScore: 42,
    riskScore: 86,
    riskLevel: "High",
    label: "Low Liquidity Warning",
    reason: "Price movement and risk score are high; dividend thesis is not supported by current data.",
    risks: ["High volatility", "Missing dividend support for income strategy"],
    trend: [12, 11.8, 11.4, 11.9, 11.1, 10.9, 10.7, 10.4, 10.8, 10.6, 10.5, 10.2],
  },
];

export const sectors: Sector[] = [
  { name: "Banking", change: 1.85, stocks: 13, bestStock: "GTCO", score: 78, tone: "positive" },
  { name: "Telecom/ICT", change: 0.92, stocks: 5, bestStock: "MTNN", score: 74, tone: "positive" },
  { name: "Consumer Goods", change: -0.48, stocks: 19, bestStock: "BUAFOODS", score: 62, tone: "danger" },
  { name: "Industrial Goods", change: 0.15, stocks: 9, bestStock: "DANGCEM", score: 58, tone: "neutral" },
  { name: "Oil & Gas", change: -1.32, stocks: 7, bestStock: "SEPLAT", score: 45, tone: "danger" },
  { name: "Healthcare", change: 0.67, stocks: 8, bestStock: "FIDSON", score: 61, tone: "positive" },
  { name: "Agriculture", change: -0.12, stocks: 6, bestStock: "PRESCO", score: 50, tone: "warning" },
  { name: "Insurance", change: 0.33, stocks: 14, bestStock: "AIICO", score: 57, tone: "positive" },
  { name: "Services", change: 0.28, stocks: 11, bestStock: "TRANSCOHOT", score: 55, tone: "positive" },
];

export const alerts: Alert[] = [
  { title: "Low Liquidity Warning", count: 6, severity: "danger", detail: "Six stocks have weak turnover for the dividend strategy." },
  { title: "Dividend Trap Watch", count: 8, severity: "warning", detail: "High yield appears unsupported by earnings or payout cover." },
  { title: "Concentration Risk", count: 3, severity: "info", detail: "Banking exposure is above the preferred starter threshold." },
];

export const watchlist: WatchlistItem[] = [
  { symbol: "GTCO", targetPrice: 68, note: "Core bank candidate; wait for calmer entry.", movement: 1.12 },
  { symbol: "ZENITHBANK", targetPrice: 47, note: "Compare dividend cover with GTCO.", movement: 0.91 },
  { symbol: "MTNN", targetPrice: 230, note: "Strong income name; monitor payout and FX risk.", movement: 2.34 },
  { symbol: "UBA", targetPrice: 31, note: "Valuation attractive; review regional risk.", movement: -0.58 },
  { symbol: "BUAFOODS", targetPrice: 350, note: "Quality consumer name; valuation needs patience.", movement: 1.06 },
];

export const holdings: Holding[] = [
  {
    id: "h-gtco",
    symbol: "GTCO",
    company: "Guaranty Trust Holding Co.",
    sector: "Banking",
    broker: "Stanbic IBTC Stockbrokers",
    quantity: 18000,
    averagePrice: 58.4,
    currentPrice: 72.5,
    dividendsReceived: 94500,
    expectedAnnualDividend: 136800,
    thesis: "Core dividend bank holding with strong liquidity and quality earnings.",
    tag: "Core Holding",
    riskLevel: "Low",
  },
  {
    id: "h-zenith",
    symbol: "ZENITHBANK",
    company: "Zenith Bank Plc",
    sector: "Banking",
    broker: "Stanbic IBTC Stockbrokers",
    quantity: 16000,
    averagePrice: 43.2,
    currentPrice: 49.8,
    dividendsReceived: 72000,
    expectedAnnualDividend: 86400,
    thesis: "Income and valuation holding, reviewed against banking concentration.",
    tag: "Dividend Income",
    riskLevel: "Low",
  },
  {
    id: "h-mtnn",
    symbol: "MTNN",
    company: "MTN Nigeria Communications",
    sector: "Telecom/ICT",
    broker: "Stanbic IBTC Stockbrokers",
    quantity: 5200,
    averagePrice: 221,
    currentPrice: 245,
    dividendsReceived: 61200,
    expectedAnnualDividend: 104000,
    thesis: "Essential-service income holding, but payout and FX risk need monitoring.",
    tag: "Defensive",
    riskLevel: "Moderate",
  },
  {
    id: "h-bua",
    symbol: "BUAFOODS",
    company: "BUA Foods Plc",
    sector: "Consumer Goods",
    broker: "Stanbic IBTC Stockbrokers",
    quantity: 2100,
    averagePrice: 365,
    currentPrice: 380,
    dividendsReceived: 25200,
    expectedAnnualDividend: 60900,
    thesis: "Consumer staple exposure with income potential; valuation is the key review point.",
    tag: "Value Play",
    riskLevel: "Moderate",
  },
];

export const transactions: Transaction[] = [
  { id: "t1", date: "2026-01-12", symbol: "GTCO", broker: "Stanbic IBTC Stockbrokers", type: "Buy", quantity: 12000, price: 56, charges: 8200, netAmount: 680200, reference: "SIBTC-CN-001" },
  { id: "t2", date: "2026-02-18", symbol: "ZENITHBANK", broker: "Stanbic IBTC Stockbrokers", type: "Buy", quantity: 16000, price: 43.2, charges: 7600, netAmount: 698800, reference: "SIBTC-CN-002" },
  { id: "t3", date: "2026-03-04", symbol: "MTNN", broker: "Stanbic IBTC Stockbrokers", type: "Buy", quantity: 5200, price: 221, charges: 11400, netAmount: 1160600, reference: "SIBTC-CN-003" },
  { id: "t4", date: "2026-04-22", symbol: "GTCO", broker: "Stanbic IBTC Stockbrokers", type: "Dividend Received", quantity: 18000, price: 5.25, charges: 0, netAmount: 94500, reference: "DIV-GTCO-2026-F" },
];

export const documents: DocumentRecord[] = [
  { title: "GTCO purchase contract note", type: "Stanbic IBTC contract note", broker: "Stanbic IBTC Stockbrokers", relatedStock: "GTCO", date: "2026-01-12", path: "data/documents/stanbic-gtco-contract-note.pdf" },
  { title: "Portfolio statement - May", type: "Stanbic IBTC portfolio statement", broker: "Stanbic IBTC Stockbrokers", date: "2026-05-31", path: "data/documents/stanbic-may-statement.pdf" },
  { title: "GTCO dividend evidence", type: "Dividend payment proof", broker: "Stanbic IBTC Stockbrokers", relatedStock: "GTCO", date: "2026-04-22", path: "data/documents/gtco-dividend-proof.pdf" },
];

export const brokerSetup: BrokerSetup = {
  brokerName: "Stanbic IBTC Stockbrokers",
  accountNickname: "Tony Stanbic NGX",
  cscsNumber: "CSCS-LOCAL-DEMO",
  chn: "CHN-LOCAL-DEMO",
  checklist: [
    { label: "Open Stanbic IBTC stockbroking account", done: true },
    { label: "Receive online/e-trade login details", done: true },
    { label: "Confirm CSCS account number", done: true },
    { label: "Confirm CHN", done: true },
    { label: "Fund brokerage account", done: true },
    { label: "Make first small purchase", done: true },
    { label: "Confirm contract note is received", done: true },
    { label: "Confirm portfolio statement access", done: false },
    { label: "Confirm dividend/e-dividend setup", done: false },
  ],
  links: [
    { label: "Stanbic IBTC Stockbrokers", href: "https://www.stanbicibtcstockbrokers.com/" },
    { label: "Account opening", href: "https://www.sislbrokerage.com/IW/NewAccount/Account" },
    { label: "Stockbroking overview", href: "https://www.stanbicibtc.com/nigeriaholdings/Stanbic-IBTC-Holdings/what-we-do/our-business/stockbroking" },
  ],
};

export const changedItems = [
  { symbol: "GTCO", detail: "Dividend yield improved from 9.8% to 10.45%", change: 0.65 },
  { symbol: "MTNN", detail: "Price rose and opportunity score gained 3 pts", change: 2.34 },
  { symbol: "OANDO", detail: "Risk score rose 5 pts after weak price action", change: -3.21 },
  { symbol: "BUAFOODS", detail: "Dividend score improved after payout review", change: 0.5 },
  { symbol: "NESTLE", detail: "No significant change", change: 0 },
];

export const scoreDistribution = [
  { range: "0-20", count: 6, color: "#EF4444" },
  { range: "21-40", count: 18, color: "#F97316" },
  { range: "41-60", count: 42, color: "#EAB308" },
  { range: "61-80", count: 88, color: "#22C55E" },
  { range: "81-100", count: 62, color: "#10B981" },
];

export const portfolio = portfolioMetrics(holdings);

export const aiBriefing =
  "Banking and Telecom/ICT lead this scan, supported by liquidity, dividend visibility, and earnings strength. Consumer goods are mixed: BUA Foods remains interesting but valuation needs patience. Watch liquidity and dividend-trap risk before adding smaller names. This is research intelligence only; trades remain manual through Stanbic IBTC.";
